/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wv1124_android_test_NativeApi */

#ifndef _Included_com_wv1124_android_test_NativeApi
#define _Included_com_wv1124_android_test_NativeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wv1124_android_test_NativeApi
 * Method:    testBoostTimer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wv1124_android_test_NativeApi_testBoostTimer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
